# Generated by Django 5.2.4 on 2025-07-07 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id_in_sheet', models.CharField(help_text='A unique identifier for the event in the sheet (e.g., row number, custom ID)', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('person1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person4_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caldav_url', models.URLField(help_text='e.g., https://caldav.example.com/dav/calendars/user/home/')),
                ('caldav_username', models.CharField(max_length=255)),
                ('caldav_password', models.CharField(max_length=255)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(help_text='The name as it appears in the Google Sheet for this user', max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='UserCalDAVEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caldav_uid', models.CharField(help_text='The UID of the event in the CalDAV calendar.', max_length=255, unique=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sheet_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sheetevent')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'sheet_event')},
            },
        ),
    ]
